/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package analizadorlex;
import java.lang.System;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
public class Analizador {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\41\1\11\1\12\1\11\1\11\22\0\1\41\1\0\1\10"+
    "\5\0\1\20\1\20\1\16\1\6\1\17\1\7\1\4\1\16\12\3"+
    "\1\17\1\17\1\14\1\15\1\13\2\0\1\34\1\36\1\25\1\31"+
    "\1\5\1\21\1\1\1\33\1\30\2\1\1\26\1\1\1\24\1\22"+
    "\1\23\1\1\1\35\1\27\1\32\1\40\1\1\1\37\3\1\1\20"+
    "\1\0\1\20\3\0\32\2\1\20\1\0\1\20\7\0\1\12\u1fa2\0"+
    "\1\12\1\12\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\2\6\1\7\1\10\1\11\7\1\1\12\4\0\1\6"+
    "\4\0\1\13\6\0\1\14\2\0\1\15\4\0\1\16"+
    "\11\0\1\17\1\0\1\20\1\0\1\21\6\0\1\22"+
    "\2\0\1\23\1\24\1\25\2\0\1\26\1\27\1\30"+
    "\2\0\1\31\3\0\1\32\1\33\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\42\0\210\0\42\0\252"+
    "\0\42\0\314\0\356\0\314\0\42\0\u0110\0\u0132\0\u0154"+
    "\0\u0176\0\u0198\0\u01ba\0\u01dc\0\u01fe\0\u0220\0\u0242\0\u0264"+
    "\0\u0286\0\u02a8\0\42\0\u02ca\0\u02ec\0\u030e\0\u0330\0\42"+
    "\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da\0\u03fc\0\u041e\0\u0440"+
    "\0\u0462\0\u02a8\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\42\0\u050c"+
    "\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8\0\u05fa\0\u061c"+
    "\0\42\0\u063e\0\42\0\u0660\0\42\0\u0682\0\u06a4\0\u06c6"+
    "\0\u06e8\0\u070a\0\u072c\0\42\0\u074e\0\u0770\0\42\0\42"+
    "\0\42\0\u0792\0\u07b4\0\42\0\42\0\42\0\u07d6\0\u07f8"+
    "\0\42\0\u081a\0\u083c\0\u085e\0\42\0\42\0\42";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\2\7\1\10"+
    "\1\11\1\0\1\12\1\13\1\14\1\7\1\5\1\15"+
    "\1\16\1\17\2\3\1\20\2\3\1\21\4\3\1\22"+
    "\1\23\1\24\1\25\1\11\44\0\1\26\42\0\1\4"+
    "\1\27\37\0\1\26\21\0\1\30\1\0\1\31\13\0"+
    "\11\32\2\0\27\32\15\0\1\33\37\0\1\33\1\0"+
    "\1\33\26\0\1\26\23\0\1\34\15\0\1\26\20\0"+
    "\1\35\20\0\1\26\23\0\1\36\4\0\1\37\10\0"+
    "\1\26\16\0\1\40\2\0\1\41\4\0\1\42\12\0"+
    "\1\26\2\0\1\43\36\0\1\26\17\0\1\44\21\0"+
    "\1\26\30\0\1\45\10\0\1\26\21\0\1\46\17\0"+
    "\2\26\41\0\1\47\67\0\1\50\37\0\1\51\12\0"+
    "\10\32\1\52\2\0\27\32\22\0\1\53\24\0\1\54"+
    "\56\0\1\55\53\0\1\56\37\0\1\57\14\0\1\60"+
    "\57\0\1\61\40\0\1\62\47\0\1\63\43\0\1\64"+
    "\12\0\1\47\1\0\1\65\1\0\1\66\62\0\1\67"+
    "\6\0\1\70\7\0\1\71\70\0\1\72\31\0\1\73"+
    "\44\0\1\74\47\0\1\75\30\0\1\76\22\0\1\77"+
    "\62\0\1\100\41\0\1\101\43\0\1\102\17\0\1\66"+
    "\36\0\1\103\57\0\1\104\7\0\1\105\43\0\1\106"+
    "\40\0\1\107\14\0\1\110\66\0\1\111\43\0\1\112"+
    "\12\0\1\113\41\0\1\114\62\0\1\115\16\0\1\116"+
    "\43\0\1\117\64\0\1\120\43\0\1\121\43\0\1\122"+
    "\31\0\1\123\43\0\1\124\37\0\1\125\47\0\1\126"+
    "\14\0\1\127\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2176];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\1\11\1\1\1\11"+
    "\3\1\1\11\11\1\4\0\1\11\4\0\1\11\6\0"+
    "\1\1\2\0\1\1\4\0\1\11\11\0\1\11\1\0"+
    "\1\11\1\0\1\11\6\0\1\11\2\0\3\11\2\0"+
    "\3\11\2\0\1\11\3\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private int contador;
boolean error;

public boolean getError(){
     return error;
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador(java.io.Reader in) {
  contador = 0;
error=false;
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Analizador(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 126) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { error=true;
          }
        case 29: break;
        case 2: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"NUMERO ENTERO", yyline, yychar);
          }
        case 30: break;
        case 3: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"SIGNO DE PUNTUACION", yyline, yychar);
          }
        case 31: break;
        case 4: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"OPERADOR ARITMETICO", yyline, yychar);
          }
        case 32: break;
        case 5: 
          { 
          }
        case 33: break;
        case 6: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"OPERADOR RELACIONAL", yyline, yychar);
          }
        case 34: break;
        case 7: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"OPERADOR DE ASIGNACION", yyline, yychar);
          }
        case 35: break;
        case 8: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"SIGNO DE AGRUPACION", yyline, yychar);
          }
        case 36: break;
        case 9: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: F", yyline, yychar);
          }
        case 37: break;
        case 10: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"IDENTIFICADOR", yyline, yychar);
          }
        case 38: break;
        case 11: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: IF", yyline, yychar);
          }
        case 39: break;
        case 12: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"NUMERO REAL", yyline, yychar);
          }
        case 40: break;
        case 13: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"STRING", yyline, yychar);
          }
        case 41: break;
        case 14: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: INT", yyline, yychar);
          }
        case 42: break;
        case 15: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: ELSE", yyline, yychar);
          }
        case 43: break;
        case 16: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: OPEN", yyline, yychar);
          }
        case 44: break;
        case 17: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: CHAR", yyline, yychar);
          }
        case 45: break;
        case 18: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: ENDIF", yyline, yychar);
          }
        case 46: break;
        case 19: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: FLOAT", yyline, yychar);
          }
        case 47: break;
        case 20: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: CLOSE", yyline, yychar);
          }
        case 48: break;
        case 21: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: IDENT", yyline, yychar);
          }
        case 49: break;
        case 22: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: WHILE", yyline, yychar);
          }
        case 50: break;
        case 23: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: UNTIL", yyline, yychar);
          }
        case 51: break;
        case 24: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"NUMERO REAL CIENTIFICO", yyline, yychar);
          }
        case 52: break;
        case 25: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: REPEAT", yyline, yychar);
          }
        case 53: break;
        case 26: 
          { error=false; contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: BOOLEAN", yyline, yychar);
          }
        case 54: break;
        case 27: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: ENDIDENT", yyline, yychar);
          }
        case 55: break;
        case 28: 
          { error=false;contador++;
                    return new Yytoken(contador, yytext(),"PALABRA RESERVADA: ENDWHILE", yyline, yychar);
          }
        case 56: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
