
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 01 00:01:44 CDT 2015
//----------------------------------------------------

package analizadorsintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NONUNTIL = 9;
  public static final int NONCOMA = 27;
  public static final int NONPARABRE = 30;
  public static final int NONENDIDENT = 12;
  public static final int NONPARCIERRA = 31;
  public static final int NONEFE = 7;
  public static final int NONPUNTO = 26;
  public static final int NONENDWHILE = 18;
  public static final int NONIDENT = 11;
  public static final int NONREPEAT = 19;
  public static final int NONIGUAL = 23;
  public static final int NONIF = 20;
  public static final int NONENDIF = 22;
  public static final int NONWHILE = 17;
  public static final int NONOPEN = 8;
  public static final int NONDOSPUNTOS = 29;
  public static final int NONREAL = 4;
  public static final int EOF = 0;
  public static final int NONIDENTIFICADOR = 2;
  public static final int error = 1;
  public static final int NONARIT = 25;
  public static final int NONELSE = 21;
  public static final int NONENTERO = 3;
  public static final int NONCLOS = 10;
  public static final int NONFLOAT = 15;
  public static final int NONCHAR = 14;
  public static final int NONBOOLEAN = 16;
  public static final int NONPUNTOYCOMA = 28;
  public static final int NONREALCIENT = 5;
  public static final int NONINT = 13;
  public static final int NONSTRING = 6;
  public static final int NONREL = 24;
}

